#!/bin/bash
#exe=("firefox" "thunderbird" "urxvt" "pcmanfm" "rox" "qq" "linux-fetion" "urxvt -e rtorrent" "googleearth" "jsweather" "gedit" "soffice" "FBReader" "gimp" "stardict" "audacious2" "sonata" "VirtualBox" "gcalctool")
#name=("火狐浏览器" "雷鸟邮箱" "Urxvt" "Pcmanfm" "Rox" "Linux-QQ" "飞信" "BT下载" "Goole地球" "嘉善天气" "文本编辑" "OpenOffice" "电子书阅读器" "Gimp" "星际译王" "Audacious2" "Sonata" "虚拟机" "计算器")
exe=("chromium-browser --enable-plugins --app=https://www.google.com/reader/" "chromium-browser --enable-plugins --app=http://www.zhuaxia.com" "chromium-browser --enable-plugins --app=http://xianguo.com/reader" "chromium-browser --enable-plugins --app=http://web.qq.com" "chromium-browser --enable-plugins --app=http://www.1g1g.com" "gw")
name=("Google Reader" "抓虾" "鲜果" "qq" "亦歌" "嘉善公文")
for ((i=0;i<=${#exe[@]};i++))
do
exef[$i]=`echo ${exe[$i]}|sed 's/ /_/g'`
name[$i]=`echo ${name[$i]}|sed 's/ /_/g'`
out[$i]=${name[$i]}" "${exef[$i]}
done

arg=`echo ${out[@]}|xargs zenity --list --column "程序" --column "exe" --print-column 2 --hide-column 2 --width 50 --height 550 --title "快速启动" --text "选择要启动的程序"`
if [ $arg ]
	then
	arg=`echo $arg|sed 's/_/ /g'` 
	notify-send "正在启动$arg,请稍候。"
  	#echo "正在启动$arg,请稍候。"|osd_cat -d 2 -O 1 -u black -l 2 -p bottom -o 60 -c green -f "-isas-song ti-medium-r-normal--*-*-*-*-c-*-*-*"
	$arg
else
	notify-send "没有选择程序,Bye Bye!!"
	#echo "没有选择程序,Bye Bye!!"|osd_cat -d 2 -O 1 -u black -l 2 -p bottom -o 60 -c green -f "-isas-song ti-medium-r-normal--24-240-72-72-c-240-gb2312.1980-0"
	exit
fi	

