#!/bin/bash
icon="/home/xzap/.icons/tianqi/suncloud.png"
gao=260
tianqi(){
xx=$(w3m -dump "http://www.jsqx.com.cn/web/tq01.aspx")  #| zenity --progress --auto-close

count=`echo $xx|awk -F "。" '{print NF}'`
((count-=1))
(($count<10))&&gao=300
for ((i=1;i<$count;i++)) 
do
jst[$i]=`echo $xx|awk -v j=$i -F "。" '{print $j }'|sed 's/ //g'`
done 

jst[0]=`echo ${jst[1]}|awk -F "：" '{print $1}'`
jst[0]=`echo ${jst[0]}|sed 's/嘉善县气象台//'|sed 's/的天气预报//'`
jst[1]=`echo ${jst[1]}|awk -F "：" '{print $2}'`
}
shuchu(){
for k in ${jst[@]}

do
if [ $k = ${jst[0]} ]
then
echo -e "$k:"
continue
fi
echo -e "$k"|sed 's/^/    /g'
done
echo 
echo "      Now: `date`"|tr -d "CST"
#xyz=`echo $xx|awk -F "。" '{
#i = 1 
#                while (i < NF) {
#	print $i,'\n'
#	++i
#}}'`
#echo $xyz|sed 's/ //g'
}
#|zenity --progress --auto-close
#tianqi |sed '/^$/d'|zenity --text-info --title "嘉善天气" --width "380" --height "260" 

#tianqi |sed '/^$/d'|zenity --text-info --title "嘉善天气" --width "380" --height "260" --window-icon "$icon"
tianqi 
shuchu |zenity --text-info --title "嘉善天气" --width "380" --height $gao --window-icon "$icon" 
