#!/bin/bash
#解压缩rar文件
if [ ! -d rar ] 
then
mkdir -p rar
fi
for i in *
do
if [ -f "$i" ]
then
k=${i#*.}
j=${i%%.*}
case $k in
	tar)
	mkdir -p $j
	mv $i $j/$i
	(cd $j;tar xvf $i;mv $i ../rar/$i;cd ..)
;;
	gz)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;gzip -d $i;mv $i ../rar/$i;cd ..)
;;	
	tar\.gz|tgz|tar\.Z)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;tar zxvf $i;mv $i ../rar/$i;cd ..)
;;
	bz2|bz)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;bzip2 -d $i;mv $i ../rar/$i;cd ..)
;;
	tar\.bz2|tar\.bz)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;tar jxvf $i;mv $i ../rar/$i;cd ..)
;;
	Z)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;uncompress $i;mv $i ../rar/$i;cd ..)
;;
	
	zip)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;unzip $i;mv $i ../rar/$i;cd ..)
;;
	rar)
		mkdir -p $j
	mv $i $j/$i
	(cd $j;rar x $i;mv $i ../rar/$i;cd ..)
;;
esac
fi
done
