#!/bin/bash
ans=$(zenity --list --title "退出系统" --text "操作列表"\
--你要干什么? --column "选择" --column "执行" \
注销 logout 重启 reboot 关机 poweroff);
echo $ans
case $ans in
'注销')
echo "logout"
killall openbox
;;
'重启')
echo "reboot"
sudo reboot
;;
'关机')
echo "poweroff"
sudo poweroff
;;
esac
