#!/bin/bash
#=====================================
#帮助pps for linux 更好的播放的小脚本。
#xzap   xzap1982[at]gmail.com
#ver: 20090824v4
#======================一些设置===================
#pps for linux 的mplayer的地址
exe=~/usr/pps/mplayer
#抓取影片的数量。抓取几个页面的影片。
page=${1:-9}
#缓存的播放列表位置
templist=/tmp/ppslist$$
#======================开始代码========================
	while :
do
category=`zenity --list --hide-column 1 --width 150 --height 300 --title "pps的简单的播放列表" --text "选择要播放影片的类别"  --column "class" --column "分类"  "555" "动作" "556" "喜剧" "557" "爱情" "558" "恐怖" "559" "科幻" "560" "动画" "561" "战争" "562" "纪录"`
if [ $? != 0 ]
		then 
		[ -e $templist ]&&rm $templist
		exit
		
	fi
case $category in
555)fenlei="动作";;
556)fenlei="喜剧";;
557)fenlei="爱情";;
558)fenlei="恐怖";;
559)fenlei="科幻";;
560)fenlei="动画";;
561)fenlei="战争";;
562)fenlei="记录";;
esac
echo "抓取列表中，请稍等……"
[ -e $templist ]&&rm $templist
for (( i = 1; i < page; i++ )); do
let count=$page-$i
echo -n "$count"
wget http://kan.pps.tv/nlist/$category/$i.html -q -T 10 -O- 2>/dev/null | iconv -f gbk |grep -o /play/[0-9]*_*[0-9]*.*html\"\ target=\"_blank\"\>[^\u4E00-\u9FA50-9A-Za-z]**[^\u4E00-\u9FA50-9A-Za-z]*\<\/a|sed 's/<\/a//g'|sed 's/" target="_blank">/\n/g' >> $templist
echo -n ".. "
done 2>/dev/null
while :
do
url=`cat $templist|zenity --list --column "url" --column "$fenlei 分类中的影片" --hide-column 1 --width 200 --height 450 --title "pps的简单的播放列表" --text "选择要播放的影片" `
if [ $? != 0 ]
		then 
		[ -e $templist ]&&rm $templist
		break
		
	fi
url=http://kan.pps.tv$url
echo "正在分析$url中的播放链接，请稍等……"
url2=`wget $url -q -T 10 -O- 2>/dev/null | iconv -f gbk|grep  -o \(\'pps://[A-Za-z0-9]*.pps/[a-zA-Z0-9%].*|sed  "s/('\(.*\)').*$/\1/g"|sed "s/').*$//g"`
if [ -z $url2 ]
then 
echo "Sorry! 没有捕获播放地址。请手工从$url的源代码中查找pps的播放链接。"
else

echo "已经捕获播放地址$url2现在开始播放……"
sudo $exe $url2
wait
fi
done
done

