#!/bin/bash
while :
do
for i in *
do
if [[ ${i##*\.} = "torrent" ]] && [[ -z $i ]] 
then
notify-send "正在将$i移动到/home/xzap/torrent中……" 
mv $i /home/xzap/torrent/$i
wait
if [ -e /home/xzap/torrent/$i ]
	then
		notify-send "$i发送成功了"
	else 
		notify-send "$i发送失败了"
fi 
fi
done
sleep 30
done


